### ISSUE TITLE
Adjust theme for current best practices.

### ISSUE THREAD

**Issue by mikeethedude** [emulsify-ds/emulsify-wordpress-theme#21]
## Motivation

While this theme works as it is now, we want to improve the file structure and setup for current best practices found amongst the top WP themes. This includes adding the correct annotations in the style.css file and moving dependency code into an includes file.

## Known Tasks

- Move Emulsify functions and Timber specific functions/classes found in the functions.php file into something in an includes file in another directory with better commenting around what functionality these provide for the theme.
- Move php template files (single.php, page.php, etc.) into a views directory to clean up the root of this project.
- Add annotation to style.css to describe our theme when viewed in the admin dashboard. (See: [Anatomy of a Theme](https://codex.wordpress.org/Theme_Development#Anatomy_of_a_Theme) )

### Future Tasks
- Increase project documentation both within project README and https://docs.emulsify.info/
- Run [theme sniffer](https://github.com/WPTT/theme-sniffer) on project

**Comment by ModulesUnraveled** [comment]
I'd like to talk this through with whoever is doing the work. Really just about the style.css part. Ideally, we'd pull styles out of this project (like we're doing for the emulsify-drupal project) so everything would live in Compound instead... That might make it tricky since Drupal doesn't need that header info, but maybe it wouldn't hurt either... Anyway, let's just talk through it so that we make the right choice

**Comment by joetower** [comment]
@ModulesUnraveled The style.css part is literally adding a comment, something like this: 
```
/*
Theme Name: Twenty Thirteen
Theme URI: http://wordpress.org/themes/twentythirteen
Author: the WordPress team
Author URI: http://wordpress.org/
Description: The 2013 theme for WordPress takes us back to the blog, featuring a full range of post formats, each displayed beautifully in their own unique way. Design details abound, starting with a vibrant color scheme and matching header images, beautiful typography and icons, and a flexible layout that looks great on any device, big or small.
Version: 1.0
License: GNU General Public License v2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
Tags: black, brown, orange, tan, white, yellow, light, one-column, two-columns, right-sidebar, flexible-width, custom-header, custom-menu, editor-style, featured-images, microformats, post-formats, rtl-language-support, sticky-post, translation-ready
Text Domain: twentythirteen

This theme, like WordPress, is licensed under the GPL.
Use it to make something cool, have fun, and share what you've learned with others.
*/
```
 to the top of the `style.css` file which is required for the theme to be valid. It is not a file that actually includes any CSS. If you look at the style.css file in this repository so far, it simply has one comment but does not include comment like the above required-by-WordPress theme information. 

Does that change your thoughts or is there still discussion to be had?

**Comment by ModulesUnraveled** [comment]
Oh! There's a style.css in the theme root. Not the style.scss (which compiles to `dist/style.css` and is used by the theme)

... That seems like a weird place to put that kind of information, but whatever. That should be fine, and shouldn't have any effect on the components, or whether we can share twig component from Compound, so no discussion needed.

Thanks for the additional info!

**Comment by mikeethedude** [comment]
Near as I can tell, we can't really move the php template files the way we want to yet. I'm going to remove that from this issue and we'll file that away as a nice to have in the future.
