### ISSUE TITLE
Sub-theming in WordPress?

### ISSUE THREAD

**Issue by evanmwillhite** [emulsify-ds/emulsify-wordpress-theme#3]
I don't think we're "subtheming" correctly (or at all), so this is a task to make sure we are either doing it correctly or to track the work to fix it. It may entail the following, but honestly I'm not sure:

- [ ] index.php being specific to our theme?
- [ ] Getting rid of some things in functions.php?
- [ ] Getting rid of unnecessary files in root?

Helpful? links:
- https://github.com/timber/timber
- https://github.com/timber/starter-theme
- https://github.com/pixelgrade/timber-child
- https://developer.wordpress.org/themes/advanced-topics/child-themes/

**Comment by mirzu** [comment]
Anyone with Wordpress Experience could take a look at this.

**Comment by terrance-orletsky-d7** [comment]
I *may* be interested in looking at this, if the intended result will suit the needs of the project I'm working on.

@evanmwillhite  Can you please elaborate on what the Acceptance Criteria would be for the solution you propose, and what the key blockers are, presently?

**Comment by evanmwillhite** [comment]
@terrance-orletsky-d7 that is awesome! Yes, we have actually nailed down a path forward with this but I hadn't recorded anything in here yet so thanks for the reminder. Here's our list as it stands currently below:

**Specific tasks**
1. Move Timber starter code from [functions.php](https://github.com/emulsify-ds/emulsify-wordpress-theme/blob/master/functions.php) into a new `inc/timber.php` file. Where the new file gets included in the functions.php file, add some helpful comments as to what this functionality is.
2. Move Emulsify-specific Twig functions in [functions.php](https://github.com/emulsify-ds/emulsify-wordpress-theme/blob/master/functions.php) to a new `inc/emulsify.php` file. Again, where the new file gets included in the functions.php file, add some helpful comments as to what this functionality is.

**General Tasks**
1. Increase project documentation both within project README and https://docs.emulsify.info/
2. Run [theme sniffer](https://github.com/WPTT/theme-sniffer) on project
3. Look over popular Wordpress themes (e.g., [twentytwentyone](https://github.com/WordPress/twentytwentyone)) and make sure that we follow conventions where it makes sense. We may break conventions in some ways, but let's make sure they're purposeful. One thing we could do for example is to follow [the template directory structure](https://github.com/WordPress/twentytwentyone/tree/trunk/template-parts) for [Wordpress-specific template files](https://github.com/emulsify-ds/emulsify-wordpress-theme/tree/master/templates).

**Comment by mikeethedude** [comment]
A lot has changed with how we approach WP themes since this was originally written. I'm going to close this issue in favor of a new one around making this theme cleaner and closer to best practices.
