### ISSUE TITLE
build-storybook is copying the entire repo to .out

### ISSUE THREAD

**Issue by kitduncan** [emulsify-ds/emulsify-wordpress-theme#7]
I've just tried this with a fresh pull of the repo as follows (Steps to reproduce)

`$ git clone ...`
`$ yarn setup`
`$ yarn build`
`$ yarn build-storybook`

Observed Behaviour: everything in the root of the repo is copied to the `.out` directory

Expected behaviour: Only static storybook build artefacts should be copied to `.out`

Have I missed something or is this misbehaving? Great work on the theme stack!

**Comment by evanmwillhite** [comment]
@kitduncan thanks for kicking the tires on this! Also, thanks for bringing up this issue - I have submitted a PR for it [here](https://github.com/emulsify-ds/emulsify-wordpress-theme/pull/8). 

Also, we're aiming for a beta release of this project next quarter so you'll start seeing some PRs come in for refactoring, cleaning up and hopefully making the developer experience more refined in general. We're getting to use this on a solid client project and have learned a lot!

**Comment by kitduncan** [comment]
I actually took the plunge and used what you've started here as a boilerplate for a production client build, understanding that there are a few dead ends here and there at present. I love the concept, hopefully, I can contribute a little bit here and there.

**Comment by evanmwillhite** [comment]
We would love that! Thanks so much for the review too. Merged!
